// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpEd5Dv8YuHyiFAFbtcdPmMEXGGPRaZs',
    appId: '1:898153202674:web:79ae2f4f1337fe55b3616b',
    messagingSenderId: '898153202674',
    projectId: 'loopin-j',
    authDomain: 'loopin-j.firebaseapp.com',
    storageBucket: 'loopin-j.firebasestorage.app',
    measurementId: 'G-WM9GN75HGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpW2TH9fzSL45LPEx_b52f9rEIey72YWs',
    appId: '1:898153202674:android:d321a3b2f0226d6fb3616b',
    messagingSenderId: '898153202674',
    projectId: 'loopin-j',
    storageBucket: 'loopin-j.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVLG4eYH2zRRIUtlB95d_0--Nh-vlUExY',
    appId: '1:898153202674:ios:81be33527db52856b3616b',
    messagingSenderId: '898153202674',
    projectId: 'loopin-j',
    storageBucket: 'loopin-j.firebasestorage.app',
    iosBundleId: 'com.example.loopinJApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVLG4eYH2zRRIUtlB95d_0--Nh-vlUExY',
    appId: '1:898153202674:ios:81be33527db52856b3616b',
    messagingSenderId: '898153202674',
    projectId: 'loopin-j',
    storageBucket: 'loopin-j.firebasestorage.app',
    iosBundleId: 'com.example.loopinJApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzpEd5Dv8YuHyiFAFbtcdPmMEXGGPRaZs',
    appId: '1:898153202674:web:b3afe6345e1f0b82b3616b',
    messagingSenderId: '898153202674',
    projectId: 'loopin-j',
    authDomain: 'loopin-j.firebaseapp.com',
    storageBucket: 'loopin-j.firebasestorage.app',
    measurementId: 'G-3J34PGJZG6',
  );
}
